#pragma once

#define SW_MAJOR_VERSION	1
#define SW_MINOR_VERSION	1
#define SW_REVISION		1
#define SW_TEST_NUMBER		1

#define SW_MACRO_COMPANY					"HIT Automotive"
#define	SW_MACRO_PRODUCT					"SW"
#define SW_MACRO_VERSION_STR_EXPAND(tok)	#tok
#define SW_MACRO_VERSION_STR(tok)			SW_MACRO_VERSION_STR_EXPAND(tok)
#define SW_MACRO_VERSION					SW_MACRO_VERSION_STR(SW_MAJOR_VERSION) "." SW_MACRO_VERSION_STR(SW_MINOR_VERSION) "." SW_MACRO_VERSION_STR(SW_REVISION) "." SW_MACRO_VERSION_STR(SW_TEST_NUMBER)

#define SW_MACRO_STRVERSION1				SW_MACRO_VERSION_STR(SW_MAJOR_VERSION) "." SW_MACRO_VERSION_STR(SW_MINOR_VERSION) "." SW_MACRO_VERSION_STR(SW_REVISION) "." SW_MACRO_VERSION_STR(SW_TEST_NUMBER) "\0"
#define SW_MACRO_STRVERSION2				SW_MAJOR_VERSION,SW_MINOR_VERSION,SW_REVISION,SW_TEST_NUMBER
#define SW_MACRO_COMPANY_NAME_STR			"HIT Automotive"
#define SW_MACRO_LEGAL_COPYRIGHT_STR		"Copyright (C) 2024 HIT Automotive"
#define SW_MACRO_PRODUCT_NAME_STR			"HIT Automotive SW"

